---
- name: Check if iterm2 config is differ
  shell: |
    diff <(plutil -convert binary1 -o - ./com.googlecode.iterm2.plist | md5 -q) <(md5 -q ~/Library/Preferences/com.googlecode.iterm2.plist)
  args:
    chdir: roles/mac/files/Library/Preferences
    executable: /bin/bash
  register: diff_result
  always_run: true
  failed_when: false
  changed_when: diff_result.rc != 0
  notify:
    - Restore iterm2 configuration

- name: Check if getmail plist should be created
  pause:
    prompt: "Copy getmail plist?(y/n)"
  register: yn

- name: Copy getmail plist
  template:
    src: Library/LaunchAgents/local.tatsuya.kurokawa.getnewmail.plist.j2
    dest: ~/Library/Preferences/local.tatsuya.kurokawa.getnewmail.plist
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0600
  when: yn.user_input == "y"

- name: Create alias symlink
  file:
    src: "{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    state: link
  with_items:
    - "{{ symlinks }}"

- name: Install ricty fonts
  shell: |
    cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts && fc-cache -vf
  args:
    creates: "{{ ansible_user_dir }}/Library/Fonts/Ricty-Bold.ttf"

- name: Setup OS X defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  notify:
    - "{{ item.notify | default(omit) }}"
  with_items:
    - "{{ osx_defaults }}"
